#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Pg.LetsExercise.Plugins.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class DataverseContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Pg.LetsExercise.Plugins.Model.pg_exercisegoal"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Pg.LetsExercise.Plugins.Model.pg_exercisegoal> pg_exercisegoalSet
		{
			get
			{
				return this.CreateQuery<Pg.LetsExercise.Plugins.Model.pg_exercisegoal>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Pg.LetsExercise.Plugins.Model.pg_exerciserecord"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Pg.LetsExercise.Plugins.Model.pg_exerciserecord> pg_exerciserecordSet
		{
			get
			{
				return this.CreateQuery<Pg.LetsExercise.Plugins.Model.pg_exerciserecord>();
			}
		}
	}
}
#pragma warning restore CS1591
