# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET-Server-Build

on:
  push:
    branches: [ "feature/power-platform-build" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write  # Allows writing test reports
  pull-requests: write  # Allows reporting results on PRs
  
jobs:
  build:

    runs-on: windows-latest

    env:
      SOLUTION_PATH: src\server\Pg.LetsExercise\Pg.LetsExercise.sln
      TEST_ASSEMBLY_PATH: src\server\Pg.LetsExercise\**\bin\Release\*.Tests.dll
      VSTEST_CONSOLE: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
      PP_SOLUTION_NAME: LetsExercise
      PP_MAPPINGS_FILE: lets-exercise-mappings.xml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # hack, but necessary until GitHub Actions for Power Platform support all pac commands
      - if: ${{ false }} # this will never run, but will force powerplatform-actions to download
        name: force-pac-download
        uses: microsoft/powerplatform-actions/unpack-solution@latest
        with:
          solution-file: fake.zip
          solution-folder: fake

      - name: Set PAC path
        shell: pwsh
        run: |
          $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
          Write-Host "Actions Path: $actionsPath"
          if ($env:RUNNER_OS -eq "Windows") {
            Write-Host "Actions executed on Windows"
            $array1 = Get-ChildItem $actionsPath -Recurse
             Write-Host "Contents of array1:"
            $array1 | ForEach-Object { Write-Host $_.FullName }         
            $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac\tools\pac.exe')}
          }
          else {
            $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac_linux/tools/pac')}
          }
          if ($array -eq $null -or $array.Count -eq 0) {
            Write-Error "PAC executable not found"
            exit 1
          }
          $pacPath = $array[0].Directory.FullName
          Write-Host "PAC Path: $pacPath"
          echo "$pacPath" >> $env:GITHUB_PATH
          echo "##vso[task.setvariable variable=PATH]$pacPath;$env:PATH"


      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_PATH }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_PATH }} /p:Configuration=Release /p:Platform="Any CPU"

      - name: Run xUnit tests with Visual Studio 2022 Test Runner
        run: |
          $testAssemblies = Get-ChildItem -Path "${{ env.TEST_ASSEMBLY_PATH }}" -Recurse
          foreach ($assembly in $testAssemblies) {
            & "${{ env.VSTEST_CONSOLE }}" $assembly.FullName /Logger:trx
          }

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()  # Ensures test results are published even if tests fail
        with:
          name: xUnit Test Results
          path: "**/*.trx"
          reporter: dotnet-trx

      - name: Pack Unmanaged Solution
        run: |
          mkdir -p artifacts/unmanaged
          pac solution pack --zipfile artifacts/unmanaged/${{ env.PP_SOLUTION_NAME }}_unmanaged.zip --folder solutions --packagetype Unmanaged --map ${{ env.PP_MAPPINGS_FILE }}

      - name: Pack Managed Solution
        run: |
          mkdir -p artifacts/managed
          pac solution pack --zipfile artifacts/managed/${{ env.PP_SOLUTION_NAME }}_managed.zip --folder solutions --packagetype Managed --map ${{ env.PP_MAPPINGS_FILE }}

      - name: Upload Unmanaged Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unmanaged-solution
          path: artifacts/unmanaged/${{ env.PP_SOLUTION_NAME }}_unmanaged.zip

      - name: Upload Managed Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: managed-solution
          path: artifacts/managed/${{ env.PP_SOLUTION_NAME }}_managed.zip

